### ISSUE TITLE
Exceeded max number of errors in dla.maxErrorCount: 20 Data Assistant Update Failed, see messages for details

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#100]
Where are the messages and how do I change the max error count?

**Comment by ChrisBuscaglia** [comment]
https://github.com/Esri/data-assistant/issues/35

**Comment by MikeMillerGIS** [comment]
thanks chris, guess I should have searched.

**Comment by ChrisBuscaglia** [comment]
@MikeMillerGIS need to determine if it's a setting or just prints all the errors - not sure what the harm would be?

**Comment by MikeMillerGIS** [comment]
I think we should just print the errors and not restrict them.  We could ask Steve to just remove this.

**Comment by ChrisBuscaglia** [comment]
@MikeMillerGIS agreed.

**Comment by ChrisBuscaglia** [comment]
change is here: dla.py -  `maxErrorCount` = 20 # max errors before a script will stop`

**Comment by MikeMillerGIS** [comment]
- [ ] Create a bad mapping file that will create a series of errors, ensure all errors are printed

**Comment by MikeMillerGIS** [comment]
did some bad mapping, worked
