### ISSUE TITLE
After making XML file, reload crashes if FC has no records

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#103]
I made a mapping for FGDB FC to FGDB FC. The source has no records. I made the xml file, but when you try to load it back, it crashes Pro.

Here's the data to repo.
[voltageReg.zip](https://github.com/Esri/data-assistant/files/733863/voltageReg.zip)

**Comment by MikeMillerGIS** [comment]
@SteveGrise Do you know if this is still an issue?  I will add it to the milestone for testing and if a bug, move it version 3

**Comment by SteveGrise** [comment]
@MikeMillerGIS I'm not sure if this is fixed, should be on the list for testing/acceptance.

**Comment by SteveGrise** [comment]
Was not able to repro the exception, added some defensive code and tested with no //Data/Row in config file.

**Comment by previnWong** [comment]
verified, closing.
