### ISSUE TITLE
Change name of Append Data GP script

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#104]
@ChrisBuscaglia @SteveGrise should we change the name of the tool?  I was confused when I look at my history since there is a core append data command.

![image](https://cloud.githubusercontent.com/assets/2707285/22377594/8e323c2e-e480-11e6-9bc3-6912bc34bc6b.png)

**Comment by SteveGrise** [comment]
It does use the underlying Append tool, but maybe 'Stage and Append Data'
would be better. With the intermediate/stage/preview addition it's worth
thinking about some changes to names to indicate what is actually
happening...
