### ISSUE TITLE
Access all data, like the preview, to do manually manipulation

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#106]
@SteveGrise I know we discuss this tool and that the tool will run all the files and then let you work with the GDB and then pick up the process.  I see one issues with the preview gdb.  

When working on the Utility Network, we only have 7 features class.  We are loading 20+ source FC's into those 7.  The staging GDB create a layer based on the target name.  So if the same target layer is listed more than once, it is overwrite by the next file that uses that target.  Can we make unique names in the preview gdb for the layer based on source-target file?

**Proposed Change:**
Source layer - wCurbStop
Target Layer - WaterDevice
Temp GDB FC name could be:
  - wCurbStop_WaterDevice
  - wCurbStopToWaterDevice

**Comment by SteveGrise** [comment]
Yes, that is a reasonable change. In the preview case it's probably ok
because there is a datestamp appended every time it is run, but in the
staging case the source_target approach would be good - except there are
limits on file name length.

**Comment by SteveGrise** [comment]
Staging is addressed by fix for #117 - this issue addresses the intermediate dataset name only.

**Comment by previnWong** [comment]
Verified.  Only slight gotcha is that the preview FC has date and time to the minute stamped on the name.  If the the dataset is small, and you run couple FC previews within a minute, they will overwrite each other.  I think a note on the doc side is fine to cover this.
No issue in staging.
