### ISSUE TITLE
Staging data - Expose DLA.gdb location

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#109]
Now that we are exposing the dla gdb, can we allow the user to specify the location?  In discussion, can we add this in the source to target mapping?

**Comment by ChrisBuscaglia** [comment]
@MikeMillerGIS if this is added, I'd recommend that we put this in the standard settings location.  @SteveGrise I do think that this will require a bit of testing since a number of issues were resolved in regards to project GDBs and moving it to the dla.gdb.

**Comment by SteveGrise** [comment]
The layers are added to the map after processing, and the layer data source properties contains the location of the files...

**Comment by MikeMillerGIS** [comment]
I see what, when I initially ran it, I did not have a map I think or never looked at it
