### ISSUE TITLE
Ignore field case

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#113]
@SteveGrise I have found that when I switch databases, which may force a case change, the field calculator part of DA fails.  

Can we add the following function and replace all names.index() with it?  I tested this and it works nicely

```
def getFieldIndexList(values,value):
    for idx, val in enumerate(values):
        if val.upper() == value.upper():
            return idx
```

**Comment by SteveGrise** [comment]
Yes, that is a good thing to fix.

**Comment by MikeMillerGIS** [comment]
pr pushed against correct branch.

**Comment by MikeMillerGIS** [comment]
resolved, thanks!
