### ISSUE TITLE
Need to get domains from layerfiles - for Enterprise GDBs

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#120]
@MikeMillerGIS @pLeBlanc93 @ChrisBuscaglia Looks like .lyrx files will be a better way to store SQL DB connection properties rather than creating a .sde connection file location. 

I need some help to figure out how to get from the .lyrx string to the feature class/domains for DomainMapping use. Right now I have: 

using (ArcGIS.Core.Data.Geodatabase geodatabase = new Geodatabase(db)) // this is deprecated
using (ArcGIS.Core.Data.Table tab = geodatabase.OpenDataset<ArcGIS.Core.Data.Table>(table))

I have this working for File GDB and is was working with the sde connection file approach, but now I need to find a way to get to the database table/field from the layer. Ideas?

**Comment by SteveGrise** [comment]
Have a resolution for this. Will now obtain domain values for .lyrx, file gdb, and Sql gdb cases.

**Comment by previnWong** [comment]
verified. shows domains from lyrx file pointing to EGDB.

**Comment by MikeMillerGIS** [comment]
verified also
