### ISSUE TITLE
Domain Map - no resetting back to blank

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#124]
Using Domain Map, when you select a value, there is no way to revert it back to blank other than deleting and adding a row.
![image](https://cloud.githubusercontent.com/assets/11183838/23482055/8d35b76c-fe82-11e6-98bf-75c5d4a6c4ff.png)

**Comment by previnWong** [comment]
verified. resolved.

**Comment by MikeMillerGIS** [comment]
looks good
