### ISSUE TITLE
copy needs to have additional clause to handle null

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#127]
If my source field allows null, but the target field does not allow null, and I use COPY, i need another clause/conditional to handle when I come across null.  Like the case of "OTHERWISE" in value map.

This shows up when you try and append data using the config file.

**Comment by SteveGrise** [comment]
You should be able to use (None) as a source for mapping to a domain value now.

**Comment by previnWong** [comment]
@SteveGrise this is not about domain mapping, this is about using COPY.  Seems it need to have a catch all in there.
![image](https://cloud.githubusercontent.com/assets/11183838/24160417/f95a3f02-0e1e-11e7-9af3-ac6589e526d0.png)

Need a fall back value in case rows in the source has nulls and the target field does not accept nulls.  This way, a value can be forced in like "unknown".

**Comment by SteveGrise** [comment]
Oh right, I think this is a ValueMap not a Copy.

**Comment by ChrisBuscaglia** [comment]
Closing this issue, should be able to use value map to take null values and make them something else.
