### ISSUE TITLE
Failing to Append Data or Stage Data

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#128]
Having issues trying to append or stage data.  When as far as to

1) not have any fields maps
2) SetValue to some hard coded value
3) followed the datatype and required aspects of the target in the hard coded values
4) error making staging Data

![image](https://cloud.githubusercontent.com/assets/11183838/23530430/7c8291b8-ff56-11e6-9251-ed6c508857ad.png)

**Comment by previnWong** [comment]
other data, i get these error
![image](https://cloud.githubusercontent.com/assets/11183838/23530962/f7d24da2-ff58-11e6-850a-36158d35e918.png)

**Comment by previnWong** [comment]
Running the same script I have using a old Data Assistant addin from December, the process works.
@MikeMillerGIS 
![image](https://cloud.githubusercontent.com/assets/11183838/23531409/22630028-ff5b-11e6-8e2b-721e418b0fa0.png)

**Comment by SteveGrise** [comment]
What does 'followed the datatype and required aspects of the target in the hard coded values' mean? Do you mean that 'Default' for the terminalConfiguration field should be an acceptable value? 

Without data, a config file, or a more complete listing of the errors on the updateRow() error I'm not clear what this is or how to reproduce it.

I need better examples and instructions on how to isolate the issues than a quick screen capture of an error. I've spent at least 10 minutes reading through this and I have no idea how to reproduce the issue, or how many issues you are talking about.

**Comment by previnWong** [comment]
I have couple feature classes in an enterprise geodatabase as the target.  My source is a file geodatabase.  When I mapped the data from source to target, it does not load and I get an error shown in screenshot 1 and 2.

So I did a test and had no field mappings between source and target. Instead for all fields, I choose setValue and used **0** for numeric and **Unknown** for string fields.  I made sure all required fields in the target had a value set. So at this point, there is no reliance on the source for any data.

When I run the Append Data command, it still throws the same error as screenshot 1.  If I use the addin from a December build, it loads fine with setValue explicitly set or if I do source/target field mapping.

**Comment by SteveGrise** [comment]
I spent a while putting together a test case, and it works for me. Perhaps you have some required values in the SetValue fields or there is some other issue. Please try to provide me with a small sample dataset and your config file so I can more quickly work through these issues.
![image](https://cloud.githubusercontent.com/assets/4749060/23761184/ee0643a2-04bf-11e7-927a-f5e488cf2935.png)

**Comment by previnWong** [comment]
@SteveGrise. I took the most recent release https://github.com/Esri/data-assistant/tree/Enhancements-WA1/ShareGISData/bin/Release.  This version does not append data. It just freezes.  I'm trying to append from file geodatabase to file geodatabase. No field mapping, just hard coded setValues. It freezes at different points and does not finish.  Need to manually close, I let it sit for 15 minutes.
![image](https://cloud.githubusercontent.com/assets/11183838/23910800/2361702c-0898-11e7-966e-6765f37842f9.png)

I reverted to Data Assistant from before this latest commit. and it throws python errors.
![image](https://cloud.githubusercontent.com/assets/11183838/23910880/5743f3ba-0898-11e7-800c-61a2494ab9f9.png)

Lastly, I reverted back to the the December 2016 version.  Success.
![image](https://cloud.githubusercontent.com/assets/11183838/23910924/73e8db8e-0898-11e7-8d77-642be37d5169.png)

I've attached the 2 GDB and the config file.
[sampleSource_to_GDB_DA.zip](https://github.com/Esri/data-assistant/files/842020/sampleSource_to_GDB_DA.zip)

**Comment by SteveGrise** [comment]
I'll take a look at the example, I haven't had any issues like this and it's not like I haven't done days of testing on this. I was not able to reproduce your previous issues.

**Comment by SteveGrise** [comment]
There is an error setting one of the field values. The reason it is hanging is that I was asked to set the max number of errors to a very high number, and this is taking a long time to process. If you try Preview first then you would see the errors. That would be a better workflow until the Preview runs without errors.

I am looking into the specific reason why the update cursor is failing with the data.

**Comment by SteveGrise** [comment]
subnetworkcontrollername is being created as a short integer rather than a string(64). There is an error is some code I copied from @MikeMillerGIS - my error. Will be resolved in my next commit.

**Comment by previnWong** [comment]
Awesome! Thanks @SteveGrise.  Let me know when you have another cut to test.

**Comment by SteveGrise** [comment]
it's committed now in the the release test folder.

**Comment by previnWong** [comment]
@SteveGrise The sample data used aboved works. But now when I try to use the production dataset and a layer file that has a join, the script does not seem to be able to read/export the rows to the preview dataset.
Throws the following error.
![image](https://cloud.githubusercontent.com/assets/11183838/23961808/5036ac94-0969-11e7-90b1-d4b8a06bb9db.png)
[transformerUnit_to_ElectricDevice.zip](https://github.com/Esri/data-assistant/files/845454/transformerUnit_to_ElectricDevice.zip)

attached is the source data, layer file, and config file.

**Comment by SteveGrise** [comment]
Are you able to export it? I fiddled with the join a bit to make sure there were no duplicate objectids (there would be an error message if you open the attribute table). I cannot export it with copy features:
![image](https://cloud.githubusercontent.com/assets/4749060/23973192/56e4a874-09ab-11e7-86ee-929df77cd7b6.png)

**Comment by previnWong** [comment]
I haven't tried exporting it.  But did you open the layer file and make sure the path is correctly mapped to your environment?
        "dataConnection" : {
          "type" : "CIMRelQueryTableDataConnection",
          "sourceTable" : {
            "type" : "CIMFeatureDatasetDataConnection",
            "featureDataset" : "E_Distribution",
            "workspaceConnectionString" : "DATABASE=..\\..\\..\\SourceData\\Electric\\NapervilleElectric.gdb",
            "workspaceFactory" : "FileGDB",
            "dataset" : "Transformer",
            "datasetType" : "esriDTFeatureClass"
          },
          "destinationTable" : {
            "type" : "CIMStandardDataConnection",
            "workspaceConnectionString" : "DATABASE=..\\..\\..\\SourceData\\Electric\\NapervilleElectric.gdb",
            "workspaceFactory" : "FileGDB",
            "dataset" : "TransformerUnit",
            "datasetType" : "esriDTTable"
          },

**Comment by SteveGrise** [comment]
i did get something working in my environment. at first there were multiple
objectids in the table, then i worked on the join. I'm not sure I'm seeing
the same thing you are, but even after i did some work it would not export.

**Comment by previnWong** [comment]
copy features did work for me.  no error.
![image](https://cloud.githubusercontent.com/assets/11183838/24003204/10aa3ee4-0a20-11e7-869f-835397201650.png)

**Comment by SteveGrise** [comment]
I can get that to work too - with the multiple objectids. It does create a dataset with table_fieldname, I'm looking at an issue in the fieldmap code right now that may be this problem.

**Comment by SteveGrise** [comment]
When I create a featureclass based on a view the geometry type is set to polygon - which won't export. Looking at the issue now.

**Comment by previnWong** [comment]
Seems to be loading the data fine into a EGDB.  Will load all assets into Utility Network and see what happens.

**Comment by previnWong** [comment]
closing this now. seems to load fine.
