### ISSUE TITLE
Min width of control cause the dockpane to have to be expanded to display the select button

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#131]
Because of the nature of the Pro UI and dock panes being primarily oriented vertically it would be good if the dock pane did not enforce such large minimum widths of the controls so that you can work with them without having to stretch open the dock pane. Currently the minimum width forces the button beyond the visibility in the dock pane when first initialized. There seems to be enough room to fit the combo box and button in the default width of a dock pane. 

Additional space could be saved for the row by changing the button to be the browse icon button similar to GP rather than the 'Select' text.

**Comment by SteveGrise** [comment]
Good point, I was trying to hide that button from people so they won't change it casually, but I agree it's not very clean.

**Comment by SteveGrise** [comment]
@chris-fox could not figure out how to snag the file browse icon but I think I covered the other issues.

**Comment by previnWong** [comment]
The initial xml choosing is better,
![image](https://cloud.githubusercontent.com/assets/11183838/24155761/f1c0bd50-0e11-11e7-874d-aeac89dd935a.png)

but after file chosen, the UI is still off, but atleast the scrollbars help.
![image](https://cloud.githubusercontent.com/assets/11183838/24155819/19aafa60-0e12-11e7-97e1-e9c992520485.png)

**Comment by MikeMillerGIS** [comment]
Have the same issue.  Can you set the box to auto size and move the button to the line below?
![image](https://cloud.githubusercontent.com/assets/2707285/24166610/3715bdf0-0e4a-11e7-84d4-370b06d94089.png)

**Comment by MikeMillerGIS** [comment]
i see the scroll bar, i can live with that, back to verified and closing
