### ISSUE TITLE
When not preserving globalids feature class created from a layer file is creating a polygon featureclass

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#132]
Part of extract, was always exporting 0 rows.

**Comment by SteveGrise** [comment]
One of several issues found under the catch-all bug #128

**Comment by MikeMillerGIS** [comment]
verified - 
![image](https://cloud.githubusercontent.com/assets/2707285/24177017/1fe40746-0e76-11e7-9494-06dba60e122e.png)
