### ISSUE TITLE
Domain Map not loading source list

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#133]
With the latest commit https://github.com/Esri/data-assistant/commit/0f4f343baab63ce3c1efe141fb9b4bd4ef0312ef

When creating a new config file, Loading domain on source and target with valid domains, shows a pop up error.  Source list is blank.
![image](https://cloud.githubusercontent.com/assets/11183838/24020057/df51d810-0a57-11e7-955c-26497e011d9d.png)

**Comment by previnWong** [comment]
It cause by the relative(portable) path.  If I make a new config, the source is stored relative.
```
    <Project>UtilityNetwork_AssetPackage.aprx</Project>
    <Source>Transformer.lyrx</Source>
```
If i try Load Domain with that value, it shows the error pop up.
If I change the source path to the full path
```
    <Project>UtilityNetwork_AssetPackage.aprx</Project>
    <Source>C:\Solutions_UtilityNetwork\Projects\UtilityNetwork_AssetPackage\UtilityNetwork_AssetPackage\Transformer.lyrx</Source>
```
If I load domain with this setting, it loads and reloads fine.

**Comment by SteveGrise** [comment]
In the NapervilleElectric Transformer dataset I have there is no domain on the PhaseDesignation field, I believe the tool is reporting this as designed.

![image](https://cloud.githubusercontent.com/assets/4749060/24044414/915281ec-0af1-11e7-855a-cc82b9dc6f48.png)

**Comment by SteveGrise** [comment]
This is what I see with the latest build. I saved the layer file to a subfolder to be like your example. 
![image](https://cloud.githubusercontent.com/assets/4749060/24044716/e500e148-0af2-11e7-8d64-af92860ed055.png)

**Comment by previnWong** [comment]
You can try it on OperatingVoltage as well. it has a domain.  Change back the config to just have relative to the layer file.

**Comment by SteveGrise** [comment]
I can't reproduce the issue:

![image](https://cloud.githubusercontent.com/assets/4749060/24049374/2c91accc-0b02-11e7-95ae-b8faaf45cf2a.png)

![image](https://cloud.githubusercontent.com/assets/4749060/24049430/529e1ef0-0b02-11e7-9ee2-be572c5d787b.png)

![image](https://cloud.githubusercontent.com/assets/4749060/24049349/1ad078e2-0b02-11e7-89dc-b291227526cb.png)

**Comment by previnWong** [comment]
@SteveGrise I can repro this every time.  Here is an animated gif to show the worflow I am doing.
![da_error_clip](https://cloud.githubusercontent.com/assets/11183838/24062021/0e33339e-0b17-11e7-9b51-a1e67c32d6a2.gif)

**Comment by SteveGrise** [comment]
try the latest build on Github

**Comment by SteveGrise** [comment]
@previnWong I changed this so relative paths will only be used relative to the xml file location. This will avoid confusion with the project folder and should work well for what you are doing. I updated the ReleaseTesting build. You may have to recreate files or enter the path names in .xml files for Source and Target where the relative paths are not relative to the .xml file.

**Comment by previnWong** [comment]
Tested, looks good.  From testing, it seems that if I select data from within the project folder, it will make it relative.  If the source/target is not in the project folder, it writes out the full path to data.

**Comment by MikeMillerGIS** [comment]
@SteveGrise @previnWong  what are your thoughts on otherwise.  I know we talked about this, it this better in the value map with the domain loader we discussed?

Here is my source data.  The casing has a huge list, only 4 are really used.  Feel weird not mapping them.  
![image](https://cloud.githubusercontent.com/assets/2707285/24167826/9b2990b0-0e4e-11e7-8278-be711e42e1fb.png)

**Comment by MikeMillerGIS** [comment]
Still an issue, repo case and details on https://github.com/Esri/data-assistant/issues/136

**Comment by previnWong** [comment]
closing this one, leaving #136 open till verified.
