### ISSUE TITLE
GlobalIDs not preserving when going from FGDB to EGDB

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#135]
When Appending data from a File GDB to an Enterprise GDB, the global IDs are not being preserved.  Even if you check the box in the environment variable to preserve ids
![image](https://cloud.githubusercontent.com/assets/11183838/24124609/bd8e6590-0d81-11e7-809a-cf59e4088b4d.png)

Message during tool run
![image](https://cloud.githubusercontent.com/assets/11183838/24124623/d28756a0-0d81-11e7-8008-a4e3494bb056.png)

when looking at the data, the global ids are different.
![image](https://cloud.githubusercontent.com/assets/11183838/24124633/e15215b2-0d81-11e7-9d4c-dfb35106e8c0.png)

I think it stems from the fact that the Append data tool calls the staging data tool that creates an intermittent FGDB therefore changing all the global ids.

**Comment by MikeMillerGIS** [comment]
That is correct, only egdb as a source will work

Sent from my Verizon Wireless 4G LTE DROID
On Mar 20, 2017 6:31 PM, Previn Wong <notifications@github.com> wrote:

When Appending data from a File GDB to an Enterprise GDB, the global IDs are not being preserved. Even if you check the box in the environment variable to preserve ids
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_11183838_24124609_bd8e6590-2D0d81-2D11e7-2D809a-2Dcf59e4088b4d.png&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=hoBw6CQuytVR65zzd5i-Zw&m=X1Q4fUMw1xZ5DncsRqZ7ml2tPMt1lhzmjpuTG4d_dQ4&s=Gx9YtBBpdHWWiJ6CdZny0Y3iRIWgvLB6KVD8lU5nelo&e=>

Message during tool run
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_11183838_24124623_d28756a0-2D0d81-2D11e7-2D8008-2Da4e3494bb056.png&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=hoBw6CQuytVR65zzd5i-Zw&m=X1Q4fUMw1xZ5DncsRqZ7ml2tPMt1lhzmjpuTG4d_dQ4&s=QRG_ecX2HzqO6k_7kfT7t60eZWWT8cu-CiWturKnSTo&e=>

when looking at the data, the global ids are different.
[image]<https://urldefense.proofpoint.com/v2/url?u=https-3A__cloud.githubusercontent.com_assets_11183838_24124633_e15215b2-2D0d81-2D11e7-2D9d4c-2Ddfb35106e8c0.png&d=DwMCaQ&c=n6-cguzQvX_tUIrZOS_4Og&r=hoBw6CQuytVR65zzd5i-Zw&m=X1Q4fUMw1xZ5DncsRqZ7ml2tPMt1lhzmjpuTG4d_dQ4&s=1aHzL1rfpLIeyO-lE0gA-C9e6fY1Y0s00C9FOW1mhmQ&e=>

I think it stems from the fact that the Append data tool calls the staging data tool that creates an intermittent FGDB therefore changing all the global ids.

-

**Comment by previnWong** [comment]
Closing then.
