### ISSUE TITLE
Domain Map - Unable to retrieve domain on subtype layer

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#136]
When using the domain map, if a field does not have a domain specified at the default field level and only has a domain specified at the subtype level, I am unable to retrieve a domain.

![image](https://cloud.githubusercontent.com/assets/2707285/24169882/52324c4c-0e55-11e7-9894-95fc8401957d.png)

[domanIssue.zip](https://github.com/Esri/data-assistant/files/859619/domanIssue.zip)

@SteveGrise @previnWong

**Comment by MikeMillerGIS** [comment]
Repo data attached above.  Field is material

**Comment by MikeMillerGIS** [comment]
Testing another field, it also occurs when the field has a domain, but if any subtype does not(which every field in the UN will have this as the 0/Unknown subtype is never set) it fails.

**Comment by SteveGrise** [comment]
Needed to check if domain == null when looping through subtypes:
                else if (subtypes.Count > 0)
                {
                    List<string> domainNames = new List<string>();
                    for (int s = 0; s < subtypes.Count; s++)
                    {
                        ArcGIS.Core.Data.Subtype stype = subtypes[s];
                        Domain domain = thefield.GetDomain(stype);
                        if (domain != null)

**Comment by previnWong** [comment]
verified.
