### ISSUE TITLE
Resize domain map - resizing internal table, not box in dialog

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#137]
@SteveGrise 
When trying to resize the domain map window, the internal dialog resized, but the window does not

![image](https://cloud.githubusercontent.com/assets/2707285/24169730/ef76e5cc-0e54-11e7-8aac-b09ed2445f50.png)

**Comment by ChrisBuscaglia** [comment]
@previn

**Comment by ChrisBuscaglia** [comment]
This should be handled by the new changes that Fox made for the June Release.
