### ISSUE TITLE
Appending and preserving Global IDS when target has global ID already

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#139]
Not much we can do, just logging as an FYI:

If the source feature and the target feature have the same Global ID and preserve global ID is used, the following error will be produced
 ERROR 000224: Cannot insert features - Underlying DBMS error [[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot insert duplicate key row in object 'UNAdmin.SERVICEAREA' with unique index 'UUID_42'. The duplicate key value is (a664a9dc-6550-4778-a0c2-eb98c74d4c60).]

**Comment by ChrisBuscaglia** [comment]
Adding to wiki as a known issue.
