### ISSUE TITLE
If the target has a default value and the incoming data is Null, should we set the default value

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#140]
Question raised by Previn:
My thought would be, if the the target is NONE, then if the field does not have a default value, it would store NULL as it is doing. But if the target field does have a default value, I would expect the default value to be used (in my test case 0). If there is a default value in target, my assumption is that the DB designers wants a value in there, not NULL.

My thoughts are that we should not.  We should never set a value for data unless specified for the user.

Imagine the default values was something like Critical.  Now all null values would become critical, that would be bad when someone who used to have X records of type critical now has X + # of null record =critical

**Comment by SteveGrise** [comment]
I believe whatever is set in the Field Mapper is what people will want to see. For sure we don't want the source DefaultValue to be set.

I'm not sure how we would set the target DefaultValue even if we wanted to... and how we would explain that to a user if they specifically chose a different value in the Field Mapper settings. I don't think it is a good idea to require the users to understand all of this, and it should be WYSIWYG.

**Comment by ChrisBuscaglia** [comment]
@MikeMillerGIS Any change here or can we close this issue?

**Comment by previnWong** [comment]
Let's close this for now.  If we start hearing customers  with this expectation, then we will change it.

**Comment by ChrisBuscaglia** [comment]
https://github.com/Esri/data-assistant/wiki/Known-Issues---Updated-4-27-2017
