### ISSUE TITLE
Domain Map crash - 3-21 build in bin

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#141]
Cannot use a domain map on a EGDB to EGDB using lyrx files for both.  Just crashed pro.

**Comment by MikeMillerGIS** [comment]
went back to 3-20 version and same thing.  Create a new file, select load domains pro crashes.  I added the lyr files to the main, they have a valid connection.  Both lyrx files are from an EGDB.  I did create them earlier in the day and shutdown.  I am not trying to use them again and pro crash on load domain

**Comment by MikeMillerGIS** [comment]
ah ha!  If I click the maps that those lyrx file were created from, i.e. they load.  the tool works fine.  Has to be related to https://github.com/Esri/data-assistant/issues/126.  The maps need to load to validate the initial connection

@ChrisBuscaglia we need to test lyrx files outside pro to see if the same issue occurs.  If this is a pro issue we need to get a repo case for dev

**Comment by SteveGrise** [comment]
With layer files I am checking if (MapView.Active.Map != null) because I have to use a LayerFactory and create a layer to get to the properties. 

We could extend that there should be a Map for the tools to work in general; I have avoided this except for this case and domains for web services - which I also needed a layer for.

**Comment by previnWong** [comment]
Maybe just put this in the wiki and doc "notes" to require a map in Pro to perform these tools.

**Comment by previnWong** [comment]
Add page in Wiki to tell users to have an open map in the pro project for best practice.
https://github.com/Esri/data-assistant/wiki/Have-a-map-in-the-project-when-using-this-tool
