### ISSUE TITLE
Should Lyr file be supported

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#143]
Should a Lyr file be supported?  When I select one, the path to the GDB FC is stored and not the lyrx file

![image](https://cloud.githubusercontent.com/assets/2707285/24166695/8ab321a0-0e4a-11e7-8106-500bb4325fdc.png)

**Comment by SteveGrise** [comment]
Yes, if you select the layer file from disk then the tool should store a reference to the layer file. If the layer is added to the map and then the map layer is used as an input then it should reference the feature class.

**Comment by MikeMillerGIS** [comment]
It is not, when selecting a lyr file from disk, it is apply the path to the GDB FC in the xml

**Comment by SteveGrise** [comment]
I don't get in your example why one is a .gdb and the other is a .lyrx file. I tested here and it used the layer file.

**Comment by MikeMillerGIS** [comment]
correct, I selected a lyr file in the GP Tool, it stored the path to the GDB.  I will double check

**Comment by previnWong** [comment]
Just some screen shots to show the issue.
Here, the path to lyr is defined (layer file is in same level as project file, data is not)
![image](https://cloud.githubusercontent.com/assets/11183838/25411613/93487f6a-29d2-11e7-867c-bce87b2f9880.png)

in the config, it stores the path to the data, thus all definitions set in the layer file is bypassed.
![image](https://cloud.githubusercontent.com/assets/11183838/25411635/b3b7fda2-29d2-11e7-845b-100b262541f0.png)

LYRX file type seems to work fine
![image](https://cloud.githubusercontent.com/assets/11183838/25411652/c877a9ea-29d2-11e7-9990-e65c102664d4.png)

**Comment by SteveGrise** [comment]
@MikeMillerGIS @previnWong you mean ArcMap layer files? I had no intention of supporting those, just ArcGIS Pro layer files.

**Comment by MikeMillerGIS** [comment]
ok, let mark as a know issue
