### ISSUE TITLE
Multi levels of spatial reference check

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#144]
Check the Factory code, if 0
check the names, such as
  source.spatialReference.name
  target.spatialReference.name

do you still have to write the string to the xml in a case where the source and target do not match?

**Comment by MikeMillerGIS** [comment]
Could you leave the code as is where is checks the wkid, if the do not match, still put the wkt in the xml, but  in processGlobalIds, create a spatial reference object and compare the names there?

```
# String below is representation for the 
# Geographic Coordinate system "WGS 1984" (factory code=4326)
wkt = "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],\
               PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];\
               -400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;\
               0.001;0.001;IsHighPrecision"
sr = arcpy.SpatialReference()
sr.loadFromString(wkt)
```

**Comment by SteveGrise** [comment]
I think it is problematic to compare only parts of the spatial reference properties. There is a high risk of coordinate shift that users would hate.

I would be more comfortable with just the raw string compare and letting the transformations code take care of the rest if there are differences.

**Comment by MikeMillerGIS** [comment]
Makes sense

Sent from my Verizon Wireless 4G LTE DROID

**Comment by MikeMillerGIS** [comment]
@SteveGrise last try, looks like the stuff we care about is in the beginning of the string:  What if we just compared that?

![image](https://cloud.githubusercontent.com/assets/2707285/24250076/0000df12-0fac-11e7-9f9a-3a9c7c032c2c.png)

**Comment by SteveGrise** [comment]
It's a simple approach, I'm fine with trying it that way.

**Comment by MikeMillerGIS** [comment]
i can check it in then, still hunting down the make Feature layer issue.

**Comment by MikeMillerGIS** [comment]
implemented
