### ISSUE TITLE
Relax the restriction of the spatial reference have to match for preserving global ids

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#145]
Look at using environment variables and FC to FC to project

Use 
arcpy.ListTransformations() 
https://pro.arcgis.com/en/pro-app/arcpy/functions/listtransformations.htm 

to get the transformations

**Comment by SteveGrise** [comment]
@MikeMillerGIS Do you have a coding example including the get/reset environment variables for featureclasstofeatureclass to do the transform?

**Comment by MikeMillerGIS** [comment]
We just did something simple like this.

CurrentSystem = arcpy.env.outputCoordinateSystem

CurrentTrans =  arcpy.env.geographicTransformations



transformations = arcpy.ListTransformations(sourceCoordinate, targetCoordSystem, sourceExtent)

c.spatialReference, output_spat_ref.value, desc.extent)

arcpy.env.outputCoordinateSystem = targetCoordSystem

arcpy.env.geographicTransformations = transformations



arcpy.env.outputCoordinateSystem =  CurrentSystem

arcpy.env.geographicTransformations = CurrentTrans

**Comment by SteveGrise** [comment]
Thanks, @MikeMillerGIS on your sp ref match code I see:
        sref_obj = arcpy.SpatialReference(sref)
        tref_obj = arcpy.SpatialReference(tref)
        sref_obj.loadFromString(sref)
        tref_obj.loadFromString(tref)

Is it Ok to delete the first 2 lines or am I missing something?

**Comment by MikeMillerGIS** [comment]
just pushed in an update.  I was tracking down the MakeFeature layer issue when I fix that part.  According to the help it should be

sref_obj = arcpy.SpatialReference()
tref_obj = arcpy.SpatialReference()
sref_obj.loadFromString(sref)
tref_obj.loadFromString(tref)

**Comment by MikeMillerGIS** [comment]
wkt = "GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],\
               PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]],\
               VERTCS['WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],\
               PARAMETER['Vertical_Shift',0.0],PARAMETER['Direction',1.0],UNIT['Meter',1.0]];\
               -400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119522E-09;\
               0.001;0.001;IsHighPrecision"

sr = arcpy.SpatialReference()
sr.loadFromString(wkt)

**Comment by MikeMillerGIS** [comment]
i will say implemented and closing for now

**Comment by MikeMillerGIS** [comment]
wrong one

**Comment by previnWong** [comment]
@SteveGrise still seeing mismatch SRID and global ids not preserving.
![image](https://cloud.githubusercontent.com/assets/11183838/24560465/c442ac74-15f7-11e7-91e9-731a3968074b.png)

![image](https://cloud.githubusercontent.com/assets/11183838/24560470/cb17fcac-15f7-11e7-9fb8-f21cfa9ba60d.png)

then the result from source and target
![image](https://cloud.githubusercontent.com/assets/11183838/24560480/d60a1a46-15f7-11e7-9a55-f0f8390f03f3.png)
![image](https://cloud.githubusercontent.com/assets/11183838/24560489/dc73abea-15f7-11e7-82ee-c03ebc9a1b20.png)

**Comment by SteveGrise** [comment]
It's saying the spatial references do not match. I suppose we could just
ignore spatial refs since I added the transform code. You do not have to
manually select the 'preserve globalid values' and it will have no effect.

**Comment by previnWong** [comment]
Then is the global id preserving breaking?  I have the connections from both source and target as EGDB.

**Comment by SteveGrise** [comment]
It's telling you it will not attempt to preserve globalids because the
spatial references do not match.

**Comment by SteveGrise** [comment]
@MikeMillerGIS @previnWong @ChrisBuscaglia I think we should change the logic so that the processglobalid function ignores spatial reference. The I should just handle the transformations as needed in the extract function. It seems like this will handle Previn's case better and be less confusing for other users. I am going to check in a fix that uses this approach.

**Comment by previnWong** [comment]
@SteveGrise Ran the latest add in.  Source and target are both EGDB.  I am still not seeing the GlobalIDs being preserved.

The mismatching SRID warning is now gone
![image](https://cloud.githubusercontent.com/assets/11183838/24677469/c51c3c04-193b-11e7-9f2a-9f9e4808c19e.png)

But the result, the globalids are still different.
Target
![image](https://cloud.githubusercontent.com/assets/11183838/24677488/d7032ffe-193b-11e7-9fed-a33b9fb322c2.png)

source
![image](https://cloud.githubusercontent.com/assets/11183838/24677500/dd28c1aa-193b-11e7-838f-f1bcd688fbe7.png)

**Comment by SteveGrise** [comment]
I added a more explicit print message when it will not preserve globalids. If it had determined that globalids would be preserved you would have seen a message beneath the underlined message above "Proceeding to copy rows and attempt to preserve GlobalIDs". 

You can try with the new version but it should just print that it won't preserve ids and you will see the same result. I am not sure what is incorrect in the logic.

**Comment by SteveGrise** [comment]
I suppose another direction we could go is always try to preserve globalids and just warn people when our logic says it might not work... 

I tried testing with the Preserve setting with fgdb-fgdb and it didn't raise any errors...

**Comment by SteveGrise** [comment]
Postgres test scenario:
Set env variable preserve globalids = True
export using featureclasstofeatureclass to file gdb
append from file gdb to sql db
check globalids in all datasets

**Comment by SteveGrise** [comment]
also check intermediate dataset for unique index on the globalid field

**Comment by SteveGrise** [comment]
@MikeMillerGIS @ChrisBuscaglia @previnWong update posted in ReleaseTesting folder. Keep logic the same but improve print better messages for any/all issues.

**Comment by ChrisBuscaglia** [comment]
@previnWong is this addressed?

**Comment by previnWong** [comment]
verified
