### ISSUE TITLE
Error - variable does not exist causing runtime error

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#150]
dlaFieldCalculator.py", line 404, in getValueMap
    err = "Unable to find map value (otherwise) for " + str(targetName) + ", value = " + str(sourceValue)

@SteveGrise 

targetName does not exist, should it be target value?

**Comment by SteveGrise** [comment]
Should change method definition to:
getValueMap(targetName,sourceValue,field):

and call it from the setFieldValues function the same way - 'row' and
'names' are no longer used and there is some frankenstein code in here...

**Comment by MikeMillerGIS** [comment]
will do, will make that change and submit a PR, thanks

**Comment by SteveGrise** [comment]
Updated in field Calculator code.

**Comment by previnWong** [comment]
@SteveGrise what is the workflow to test this?

**Comment by SteveGrise** [comment]
It used to happen when there was no match for a ValueMap value. To test just leave otherwise blank and do an incomplete map on source values. The code should not be reachable anymore, it was a missing variable used in the python error message.

**Comment by previnWong** [comment]
@SteveGrise no runtime python error.  But I see lots of errors (which I take as ok), but is it suppose to fail in the append process?
![image](https://cloud.githubusercontent.com/assets/11183838/24563410/0976a150-1603-11e7-9e0a-e2976ab51ecf.png)

**Comment by SteveGrise** [comment]
Yes, ValueMap is not supposed to have unmapped values so those are errors,
and if there is no otherwise that is the correct message. Before the script
was failing to write the error message.

**Comment by previnWong** [comment]
ok, I'll add notes in the wiki stating this.  ValueMap must have all mapped values, if not, Otherwise has to be used.
closing.
