### ISSUE TITLE
.NET file open error when dataset name contains .sde. (addin 4/17/17)

### ISSUE THREAD

**Issue by previnWong** [Esri/data-assistant#154]
Trying to load config file, but not able to (at default project location or user defined location)

![image](https://cloud.githubusercontent.com/assets/11183838/25017592/35c2aade-2039-11e7-9253-8616bfe40dc0.png)

![image](https://cloud.githubusercontent.com/assets/11183838/25017654/74d1d7e0-2039-11e7-8a92-3e35aa8b840c.png)

**Comment by MikeMillerGIS** [comment]
Did you rename the project?  The project you have loaded is DA_Test,aprx, in the file it is MyProject.aprx

**Comment by previnWong** [comment]
@MikeMillerGIS  I think that is a bug, I created a new project, specified the location and name, then I made a DA config file, and then that project XML value is what is stored, even though my project is at c:/download/DA_Test/

**Comment by previnWong** [comment]
@SteveGrise with the latest build, this issue still exists.  I have stock Pro (no UN flavor), no special UN database, just a pure stock postgres.  When I make a file, if I try to open it up again, it says it can't find datasources.  Still trying to verify persisting global ids in pure stock postgres.
![image](https://cloud.githubusercontent.com/assets/11183838/25240320/5c756d06-25a7-11e7-9ab9-545703a9dbc0.png)

[test841.zip](https://github.com/Esri/data-assistant/files/944343/test841.zip)

**Comment by SteveGrise** [comment]
@previnWong @MikeMillerGIS you need to assign me to issues and also include labels on any issues to link to the release I am working on. There are a pile of open issues and I did not see this one.

In this case I still have no idea what the error is - I cannot see the folder locations in the screenshots. If it's not in the project file folder there should be path included in the source/target locations. As Mike noted it is not clear which project is being opened and what the steps would be to reproduce it. The title "Doesn't recognize datasources" is completely meaningless to me.

**Comment by MikeMillerGIS** [comment]
@SteveGrise we isolated the issue.  If the owner of the GDB is SDE then the path has sde in the featureclass name.  
![image](https://cloud.githubusercontent.com/assets/2707285/25246785/b82922da-25d6-11e7-8270-b9dc124e716e.png)

The line of code below is using last index, so the path it is checking is not the SDE, but the .sde/db_925.sde

https://github.com/Esri/data-assistant/blob/Enhancements-WA1/ShareGISData/Dockpane1CheckXmlFile.cs#L109

**Comment by pLeBlanc93** [comment]
Since the path could also have .sde in it
(eg `C:/I am a folder.sde/dbcon.sde/database.sde.featureclass`), substring and indexOf can be replaced with a while loop. Python because I don't know C#:

```py
import os
path = "C:\\Users\\Win10\\Desktop\\MyProject\\localhost.sde\\a411_gas.sde.UtilityNetwork\\a411_gas.sde.Gas"
while not os.path.exists(path):
    path = os.path.dirname(path)
print(path)
'C:\\Users\\Win10\\Desktop\\MyProject\\localhost.sde'
```

**Comment by SteveGrise** [comment]
Easy test case is to edit an existing config file and add checks to the string like:
<Source>test.sde\DomainTest.gdb\Water.sde.Valve</Source>

**Comment by pLeBlanc93** [comment]
Still not working, regardless of schema.

**Comment by SteveGrise** [comment]
I need a more specific description, I did make a fix and test it on my end,
so I need to have more information about what is happening and any
data/config files you can provide.

**Comment by SteveGrise** [comment]
Found the issue, has been updated.

**Comment by previnWong** [comment]
verified handling .sde and .gdb fine now.
