### ISSUE TITLE
Preview Values dialog does not auto-expand to show entire resulting value

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#155]
Need to get addressed for release

**Comment by ChrisBuscaglia** [comment]
@previnWong @MikeMillerGIS

**Comment by SteveGrise** [comment]
Expanded the minWidth property and set Width to Auto... and it was already user resizeable.

**Comment by ChrisBuscaglia** [comment]
I just tried to size it, didn't know what worked and then realized I wasn't stretching the topmost column.

Thanks for the clarification, updated min. size and auto-sizing.

**Comment by ChrisBuscaglia** [comment]
Looks good, closing
