### ISSUE TITLE
Stage data - why do original source fields remain?

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#159]
Stage data - why do original source fields remain? @MikeMillerGIS @previnWong

**Comment by SteveGrise** [comment]
staging is different from preview, people want to manipulate the content
and maybe check that new fields look correct alongside the old fields. in
Preview the fields are there but hidden, could do the same with Stage.

**Comment by ChrisBuscaglia** [comment]
@SteveGrise found that stage is hiding fields as well, they are just hidden.
