### ISSUE TITLE
Bug - When source or target has no fields, source-target errors

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#160]
1:  Create a new polygon layer, do not add any fields
2:  Create a new source-target file

![image](https://cloud.githubusercontent.com/assets/2707285/25243778/3bada2a8-25cc-11e7-9cbc-360a6b7a899e.png)

**Comment by SteveGrise** [comment]
It's a nonsense use case but should not raise an error now.

**Comment by pLeBlanc93** [comment]
What's the point in creating the XML file? Should error out similarly to 
```
Running script SourceTargetMapping...
Source: C:\Users\Win10\Desktop\MyProject\PostgreSQL - a417_water.sde\a417_water.un.UtilityNetwork\a417_water.un.WaterAssembly
Target: C:\Users\Win10\Desktop\MyProject\PostgreSQL - a417_water.sde\a417_water.un.UtilityNetwork\a417_water.un.WaterAssembly
File: C:\Users\Win10\Desktop\MyProject\pls.xml
2 string layers with the same value is not supported by this tool, please rename one of the layers, exiting.
Completed script SourceTargetMapping...
Failed to execute (SourceTargetMapping).
```

**Comment by SteveGrise** [comment]
No thanks, it's a nonsense use case and I'm not going to debate whether
it's an error or not, we don't want the script to error out with a python
error.

**Comment by ChrisBuscaglia** [comment]
Closing this issue.
