### ISSUE TITLE
Cannot load data to a Feature Service

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#164]
Using secure feature service to my org, I am unable to load the source to target file

![image](https://cloud.githubusercontent.com/assets/2707285/25441131/6006b7c8-2a6f-11e7-8b33-3bf6f49801bd.png)

**Comment by MikeMillerGIS** [comment]
Looks like if I change the xml file to http: from https it loads, are you checking for only http://?

**Comment by MikeMillerGIS** [comment]
fix in https://github.com/Esri/data-assistant/commit/db403e620ff241da9b9e32a0056943172269cb4a

**Comment by SteveGrise** [comment]
yes, that's a weakness in the code.

**Comment by MikeMillerGIS** [comment]
are you saying even with the checks for https, we cannot load data to a secure service?

**Comment by MikeMillerGIS** [comment]
looks like I missed a few places, adding them now

**Comment by MikeMillerGIS** [comment]
i just noticed, that error is in the .net side, not the python

**Comment by SteveGrise** [comment]
yeah, I will need to check both though, there are a few parallel locations. I could probably get away with just checking for startswith('http') at this point because of the way the code works, but I like the extra check.

**Comment by MikeMillerGIS** [comment]
all fixed
