### ISSUE TITLE
Load Domains from Feature Service

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#178]
When loading domains from a feature service, the following message appears.  Not sure what it means or what it's supposed to do when I click OK, but it adds both the target and source feature layers to the map.

Zip attached with XML (FL in both source and target.

![loaddomains](https://user-images.githubusercontent.com/5614261/27405535-bf162bca-5686-11e7-99c9-14b6a2796c25.png)

[UTAH_DATA_SHARING_20.zip](https://github.com/Esri/data-assistant/files/1092832/UTAH_DATA_SHARING_20.zip)

**Comment by MikeMillerGIS** [comment]
Looks like a dev testing message.

Sent from my Verizon Wireless 4G LTE DROID

**Comment by SteveGrise** [comment]
Yes, just trying to keep you entertained !

**Comment by ChrisBuscaglia** [comment]
Yep - needed that.

**Comment by MikeMillerGIS** [comment]
yup, debug message, I will remove it in my PR
ArcGIS.Desktop.Framework.Dialogs.MessageBox.Show("service url: " + dataset);
