### ISSUE TITLE
Having no project will abort dlaPublish.py

### ISSUE THREAD

**Issue by JRosenfeldIntern** [Esri/data-assistant#189]
In dlaPublish [here](https://github.com/Esri/data-assistant/blob/master/Shared/GPTools/arcpy/dlaPublish.py#L60) the program will abort early if no project is specified in the xml file.

It looks like this was addressed by @MikeMillerGIS  in [this issue](https://github.com/Esri/data-assistant/issues/175) so maybe I'm missing something. Can someone explain why having a project here is necessary?

**Comment by MikeMillerGIS** [comment]
The project file is required when running the DA headless, outside of pro.  We really should augment to code to check the calling app and only exit when it is not Pro.
