### ISSUE TITLE
Loading layer file from project does not respect data query

### ISSUE THREAD

**Issue by JRosenfeldIntern** [Esri/data-assistant#201]
If you do not load the layer file from disc, the definition query is not respected when appending the data. That means if you were to load from the table of contents, DA uses the data source the layer file is pointing to as opposed to the layer file information (which contains the definition query).

**Comment by MikeMillerGIS** [comment]
@SteveGrise Is this expected?

**Comment by SteveGrise** [comment]
should preserve Def expression if part of layer file properties.

**Comment by JRosenfeldIntern** [comment]
Resolved/
