### ISSUE TITLE
Different sized rows should  cause an error

### ISSUE THREAD

**Issue by JRosenfeldIntern** [Esri/data-assistant#220]
At the end of appending, Data assistant checks to ensure that the target has appended correctly by counting the rows. If it does not add up, an error message appears with a warning. This should be a full on error as opposed to a warning.

The check was incorrectly seeing if the target was equal to the source in row length. I fixed that and changed the warning into an error. Will go into the next pull request.

**Comment by MikeMillerGIS** [comment]
This accounts for the target having existing features, right.  So if target has 5 and source has 10, there has to be 15 after append.

Sent from my Verizon Wireless 4G LTE DROID

**Comment by JRosenfeldIntern** [comment]
Correct. Previously, it wasn't and would literally check source row count == target row count. I fixed it so that it now does the behavior you described @MikeMillerGIS .
