### ISSUE TITLE
Subtype Fields Domain Preview not working

### ISSUE THREAD

**Issue by JRosenfeldIntern** [Esri/data-assistant#223]
In Domain Mapping, the source rows lay out all different domain values across all subtypes. In order for the preview rows underneath that mapping to show honestly, you would have to change the value in it's last iteration within the rows. For instance:

Here is an example of the layout if the source was a subtype field with domains A and B.
0 (A) - (None)
1(A) - (None)
0 (B) - (None)
1 (B) - (None)

If all of the values in source are 1, then mapping either 1(A) or 1(B) should do the same thing. The preview row, however, will not show the accurate mapping unless you map it to 1(B) due to a for loop that does not break.

**Comment by JRosenfeldIntern** [comment]
I rewrote the way the preview works. This issue will no longer occur and i have reduced the time complexity from quadratic to linear.

Will be in the next pull request.

**Comment by pLeBlanc93** [comment]
Constant time or bust.
