### ISSUE TITLE
[Question] Using pyt toolbox

### ISSUE THREAD

**Issue by JRosenfeldIntern** [Esri/data-assistant#224]
I'm looking into changing the DataLoadingAssistant.tbx to a pyt. This will help us implement any enhancements to the GPTools themselves much more easily. The problem is I don't know how to deploy that pyt into the location the tbx is located in when installing the add-on. 

The path looks something like this:
C:\Users\josh9173\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools

But of course it's different based on the installation. 

Anyone with more experience here know how to implement this?

@chris-fox @pLeBlanc93 @MikeMillerGIS @ChrisBuscaglia

**Comment by pLeBlanc93** [comment]
That occurs when the addin is installed.

**Comment by JRosenfeldIntern** [comment]
yeah I agree @pLeBlanc93 but it's got to say somewhere whereabouts it should be located. Can't seem to find it in the solution so far.

**Comment by JRosenfeldIntern** [comment]
Figured it out. Should you ever want to do this it has to be done in the Visual Studio Solution.

Add it as an item into the solution then go to it's properties. Set "Copy to Output Directory" to always. It should show up in the relative directory it is in the solution.
