### ISSUE TITLE
DA Testing Matrix

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#241]
- ArcGIS Pro
  - 1.4
  - 2.0
  - 2.1
- Toolbox is now a PYT
  - Verify all GP tools work as a script
  - Verify all GP tools work in the toolbox
- Match Library
  - Load match library from clas
  - Add to match library
  - apply match library
  - Try applying match library to field of different type
- DA Workspace
  - All feature class inputs and output
  - When input is already a layer
  - Feature Service as inputs and output
  - Non editable services as output
- Global ID exposed for mapping
  - Field mapped into target
  - Field not mapped to in target
- Domain Mapping rework
  - Ensure function works
- Input File Types
  - Shapefiles
  - Layers with Joins
- Headless/Scripted running
- Data with different projections
- preserving global id

**Comment by ChrisBuscaglia** [comment]
Closing - accounted for in issues and assigned to the Dec. Testing project
