### ISSUE TITLE
Crash when using xml that doesn't have expected nodes

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#54]
Load the attached xml -> Crash

It fails at this line when the given nodes don't exist:

SourceLayer.Text = _xml.SelectSingleNode("//Datasets/Source").InnerText

[XRayDefault.zip](https://github.com/Esri/data-assistant/files/339774/XRayDefault.zip)

**Comment by ChrisBuscaglia** [comment]
@NikkiGolding @SteveGrise we should get this in for August/Sept

**Comment by SteveGrise** [comment]
I've made some changes in this area to handle missing Xml nodes. Note that this would only happen if someone hand-edits the Xml document. I need to do a bit more testing to verify error handling but have made coding changes.

**Comment by SteveGrise** [comment]
Dev testing was positive

**Comment by NikkiGolding** [comment]
FYI @ChrisBuscaglia We will validate issues for release.

**Comment by jessnoo** [comment]
validated with attached xml.  user is now presented with error messages regarding missing nodes.
