### ISSUE TITLE
Create ability to load a series of configurations to load an entire data model to a new model

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#55]
As part of the work we are doing with the utility network, we need the ability to migrate the existing Local Government info model into the Utility Network.  This will require the capabilities of the Data Assistant, but need to run it on a series of files.

**Comment by ChrisBuscaglia** [comment]
Mike - you can append multiple files together, but not sure if this is exactly what you need. The tools will work with any source dataset.

**Comment by SteveGrise** [comment]
The easiest thing to do would be to provide a parameter option for a 'folder' and then process all of the Config files in the folder. Could also include a wildcard parameter to process a subset of files in the folder, default would be *.xml. Would that work? It would apply to Append and Replace tools, and maybe Preview.

**Comment by MikeMillerGIS** [comment]
that sounds good to me

**Comment by MikeMillerGIS** [comment]
The drag and drop capability provides this, not a priority at the moment

**Comment by MikeMillerGIS** [comment]
Closing as the drag and drop works
