### ISSUE TITLE
Ability to load a table to a featureclass

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#57]
Need the ability to load a table to a feature class using another feature layer to provide the geometry and potentially other attributes.  The scenario is a transformer table related to a pole.

**Comment by MikeMillerGIS** [comment]
This also needs to support where I want to load the Feature Class and a one or more related table that is in 1:1 relationship to a single target output

**Comment by MikeMillerGIS** [comment]
We can provide sample data

**Comment by SteveGrise** [comment]
I guess there is no (practical) way to set up a joined layer or database view then use it as the source feature class? I've done this in other cases.

It seems like the UI would change a fair bit to support this with DA - it's not a problem, but would likely be a new "Create File" tool that accepts additional parameters.

**Comment by MikeMillerGIS** [comment]
I am sure it could be done with a view or join, but we would like the tool to do this in process.

**Comment by SteveGrise** [comment]
Ok, then a table-feature class tool (or 'joiner' tool) would probably be the cleanest solution. It's either that or make the Create File tool a .NET UI so there is a better user experience than the GP tool. 

For scripting it would be Ok to keep the .py tool around, but it's a bit clumsy to start adding options to the UI.

**Comment by MikeMillerGIS** [comment]
@SteveGrise,  Just talking through this with John right now.  I misunderstood what we needed.  The immediate need is to read a layer that uses a join.  So can the Data Assistant read the source feature class/table and the fields from a join on that featureclass and table?  This should prevent reworking on the UI and just leverage Pro to specify the join.  

Does this make things any easier?

**Comment by SteveGrise** [comment]
I believe the map join approach will work, although I don't recall testing
it specifically. I've fixed the issues that come up with that in other work
so it would be an easy enhancement if there are issues.

**Comment by MikeMillerGIS** [comment]
Watching the tech transfer for 10.5/1.4 this week and I think Query layers would be the best approach here.  Then we can support any type of sql join to produce the layer that we need to load into the target.

@SteveGrise @ChrisBuscaglia what are your thoughts on this?

**Comment by MikeMillerGIS** [comment]
Looking at query layers, they only support Enterprise gdb, so for FGDB, the join approach is best, lets stick with that for now

**Comment by SteveGrise** [comment]
Completed work on domain mapping to support .lyrx files and other sources.

**Comment by previnWong** [comment]
Verified. Data Mapper shows both fields from left and right joins.
