### ISSUE TITLE
Ability to disabled changing of a field if Field Mapping was loaded from a config.

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#59]
Scenario for the utility network is that we would like to stub out the XML config files, in there we need to set the Asset Type and Asset Group fields to a default value and we would not like the user to override these.

**Comment by SteveGrise** [comment]
Most likely would just add "Editable=false" to config files so not editable in the UI. I would use python/xslt to generate these stub files, I'd like to work on setting those up as part of a 'dev package' for DA if that makes sense...

**Comment by previnWong** [comment]
@SteveGrise how is this implemented?  Is there a tag I put in the XML and at which node level?

**Comment by SteveGrise** [comment]
For Field elements, the UI IsEnabled property is bound to the IsEnabled Xml attribute:
![image](https://cloud.githubusercontent.com/assets/4749060/24212116/92140f94-0f04-11e7-91ff-4ed11c3c825b.png)

**Comment by SteveGrise** [comment]
Result is the Method panel is not enabled:
![image](https://cloud.githubusercontent.com/assets/4749060/24212169/c1b9e534-0f04-11e7-8e3a-e152386cdfb5.png)

**Comment by MikeMillerGIS** [comment]
moved to wiki - https://github.com/Esri/data-assistant/wiki/General-Wiki

**Comment by previnWong** [comment]
verified
