### ISSUE TITLE
Support loading to/from tables

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#61]
Support table - table data loading.

**Comment by SteveGrise** [comment]
Have tested GlobalID handling with Sql DBs and also ensured that domain mapping and other functionality will also work with tables.

**Comment by previnWong** [comment]
When creating a new XML file, tables that are in the TOC do not show up in the source and target datasource drop down.  Have to browse to them to get them.
![image](https://cloud.githubusercontent.com/assets/11183838/24174745/80d9578a-0e4f-11e7-8cc4-a04688516386.png)

![image](https://cloud.githubusercontent.com/assets/11183838/24174749/860ce334-0e4f-11e7-84ce-8b56607ae1db.png)

**Comment by MikeMillerGIS** [comment]
Add Table View to parameter list

**Comment by previnWong** [comment]
Closing.  Users will have to add tables using the add data icon instead of selecting from the drop down.
