### ISSUE TITLE
Enterprise GDB handling

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#63]
1. There are changes in Pro 1.3.1 for paths, handled in interactive tool but batch script issues likely 
2. Script tools to auto-generate Utility Network config files
3. Generate stub/template files
4. Use Automatch and other techniques to further automate processing

**Comment by jessnoo** [comment]
@SteveGrise What is the status of these items?

**Comment by SteveGrise** [comment]
These issues were addressed and referenced in github commits.

**Comment by jessnoo** [comment]
@SteveGrise can you reference this issue in the relevant commits or associate this issue with other relevant issues, and then close?
