### ISSUE TITLE
Append fails if target feature class is in a file geodatabase but not within a feature dataset

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#71]
The exception here is a little misleading, because it talks about deleting intermediate data and there being a lock. The problem is that the Create Feature Class gp tool fails when you attempt to create a feature class with the name 'GDB'. This name is being used because the original file geodatabase for the source feature class is named 'GDB'.

Steps to repro:
1. Create a file geodatabase named 'GDB' and a file geodatabase named 'GDB1'
2. Copy a feature class to the GDB and GDB1 geodatabases
3. Setup a mapping file from the FC in GDB to the FC in GDB1
4. Run the append tool

A Fatal Error occurred
Python Error messages:
Traceback Info:
  File "C:\Users\chri4849\AppData\Local\ESRI\ArcGISPro\AssemblyCache{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaExtractLayerToGDB.py", line 88, in extract
    retVal = exportDataset(xmlDoc,sourceLayer,dla.workspace,targetName,rowLimit)
  File "C:\Users\chri4849\AppData\Local\ESRI\ArcGISPro\AssemblyCache{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaExtractLayerToGDB.py", line 133, in exportDataset
    arcpy.CreateFeatureclass_management(workspace,targetName,template=sourceLayer,spatial_reference=targetRef)
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 1394, in CreateFeatureclass
    raise e
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\management.py", line 1391, in CreateFeatureclass
    retval = convertArcObjectToPythonObject(gp.CreateFeatureclass_management(_gp_fixargs((out_path, out_name, geometry_type, template, has_m, has_z, spatial_reference, config_keyword, spatial_grid_1, spatial_grid_2, spatial_grid_3), True)))
  File "c:\program files\arcgis\pro\Resources\arcpy\arcpy\geoprocessing_base.py", line 506, in <lambda>
    return lambda *args: val(_gp_fixargs(args, True))
Unable to export data, there is a lock on the intermediate feature class: C:\Users\chri4849\AppData\Local\ESRI\ArcGISPro\AssemblyCache{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.gdb\GDB

**Comment by chris-fox** [comment]
This problem is more common then I originally thought and easier to reproduce. The problem will occur if the output feature class is in a file geodatabase and not within a feature dataset. For example in the user's case:

C:/Data/CommunityTest/ProcessedData/Billings.gdb/Processed

The issue occurs at the line below:

https://github.com/Esri/data-assistant/blob/master/ShareGISData/GPTools/arcpy/dla.py#L720

Using the string above Billings,gdb is the string selected from the list and after it run through the nameTrimmer function 'GDB' is returned. When used to create a new feature class it fails because it is an invalid feature class name.

It seems like the following code could be used to return the last item in the last which should represent the feature class name, but it is not clear if there was another reason for returning the second to last item in the list.

fullname = parts[-1]

**Comment by chris-fox** [comment]
@SteveGrise, I just found something new. Notice how the path described above has paths with forward slashes. I can reproduce this in 1.3.1. It seems the tool is expecting backslashes for the path to local datasets which seems to be why it gets to the line of code described above. If in the xml I change the slashes to backslashes then everything is fine.

**Comment by MikeMillerGIS** [comment]
url.path.normpath to the rescue!

**Comment by SteveGrise** [comment]
@chris-fox I have made many changes over the last several weeks to better support different layer types and data source properties. Please try with the latest development branch code. The 'C:/' style strings should never occur. Also note users may need to recreate some files created with the Sept 15 release to ensure that layer strings are handled correctly.

**Comment by chris-fox** [comment]
@SteveGrise, yes I cannot reproduce this in the developer branch.

**Comment by jessnoo** [comment]
@chris-fox @ChrisBuscaglia 
validated
