### ISSUE TITLE
Update gitignore file to exclude binary and build files from the repo

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#73]
We shouldn't include build files in the repo as they change with every build and add unnecessary files to the repo. To share the compiled add-in with the repo you could add a post build action to copy the add-in to the root folder of the solution and make it available in the repo. 
# Build results

[Dd]ebug/
[Dd]ebugPublic/
[Rr]elease/
[Rr]eleases/
x64/
x86/
bld/
[Bb]in/
[Oo]bj/
[Ll]og/

**Comment by SteveGrise** [comment]
I added this because people asked me to do it. I guess I can remove it, but
they will just ask me to add it again with another bug.

**Comment by chris-fox** [comment]
I passed this info along to @lindsayking and she agreed. You can still include the compiled add-in as a separate file at the root of the repo to share with people, add a build event to xcopy it to the solution folder. I am just saying we should not include the bin or obj folders in the repo with the compiled dlls and duplicate copies of the python files and toolboxes.

**Comment by SteveGrise** [comment]
I don't mind removing this, just this week someone asked me to add this to
a different repo though. Do you have an example of 'add a build event to
xcopy it to the solution folder', I haven't done that before. Or maybe I
just explicitly include the addin in the build folder since that's where
people would look for it.

**Comment by chris-fox** [comment]
I thought it would be as easy as adding something like below to the post-build event command line in the project properties. Unfortunately it seems that packaging the of the add-in occurs after the post build event is fired so the add-in doesn't exist to copy yet.

xcopy "$(TargetDir)_addin_name_.esriAddinX" "$(SolutionDir)"

A colleague mentioned setting up another project in the solution that has a build dependency on the add-in project which forces the add-in to build first then the other project builds and there you will have an opportunity to copy the add-in to another location. I wasn't a big fan of that approach, In another repo I have just been copying it manually when I want to update the version in the repo.

**Comment by SteveGrise** [comment]
Tried several approaches, none seem to work well because the files are already in the repo. Any ideas? My latest attempt is checked into the development branch.

**Comment by chris-fox** [comment]
Check out my fork below. I updated the gitignore and added a commit to remove all the bin and obj files. the gitignore works after this.

https://github.com/chris-fox/data-assistant

**Comment by SteveGrise** [comment]
Sweet, that did the trick!

**Comment by jessnoo** [comment]
@SteveGrise is this addressed?

**Comment by SteveGrise** [comment]
I tried a number of approaches but they do not work with this repo. We
could put the addin in another folder, it would be a manual step but should
work.

**Comment by chris-fox** [comment]
@SteveGrise, the gitignore seems to be working fine, you just need to make another commit to the repo removing the binary files. I did this in a separate branch and just submitted a pull request.

**Comment by SteveGrise** [comment]
Most changes committed earlier, one addition made today *.txt to exclude list.

**Comment by chris-fox** [comment]
Verified in Sprint 2 branch
