### ISSUE TITLE
Handle Spatial reference FactoryCode=0

### ISSUE THREAD

**Issue by SteveGrise** [Esri/data-assistant#77]
It appears that the FactoryCode property can be 0 instead of blank/None to indicate a custom spatial reference.

**Comment by ChrisBuscaglia** [comment]
@SteveGrise What transformation is applied when going from a custom proj. SR to a geographic?

**Comment by SteveGrise** [comment]
The tool just uses Append to handle the spatial reference transformation.

**Comment by SteveGrise** [comment]
Updated.
