### ISSUE TITLE
When Source or Target dataset includes only stock fields, OID, Shape, ShapeLength create file fails

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#78]
When attempting to load data without extended fields, Source-Target configuration file tool fails.

Repro Steps:
1. Create a new FC without extended fields
2. Use as a source for Source-Target configuration file

**Comment by SteveGrise** [comment]
The title should read "Provide a better error message if there are no user defined fields". There is no need to use these tools if there are no user-defined fields. It's a nonsense use case that should raise an error.

**Comment by ChrisBuscaglia** [comment]
@SteveGrise Wouldn't it be easier to just create the file instead of trapping the error?  One thing that I've found difficult is the file based approach.  During a design I may have to add fields to counter a source that was unknown at the time of the target being created.  I basically have to re-create the file every time since the tool is reading from the XML for fields and not the source-target datasets.  Is there a way to read the fields directly and then write the field maps only to the XML?

**Comment by jessnoo** [comment]
Closing issue as the workflow doesn't make sense for the tools. Users could use core Pro tools to accomplish this.
