### ISSUE TITLE
New mapping file path uses previous files path

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/data-assistant#79]
Reported by @jessnoo 

set up:
fgdb1 - evacuationroute
fgdb2 - evacuationroutetarget
hosted fs - called evacuationroutetarget (eg http://services.arcgis.com/8KEQHzVdm3qDSW1h/arcgis/rest/services/EvacuationRouteTarget/FeatureServer/0 where the 0 layer name is EvacuationRouteTarget)

Map with fgdb1 evacuationroute and the hosted feature service loaded into it
Another map with fgdb2 layer loaded in it and called evacuationroutetarget

Repro Steps:
1. Create a new mapping file that fgdb to fgdb --- use the browse buttons and navigate to input layers
2. open file in data mapper
3. run append
4. Create a new mapping file that is fgdb to fs -- use the layers in the map
>> New mapping file has old path in it
5. load

**Comment by MikeMillerGIS** [comment]
@jessnoo is this still an issue?

**Comment by SteveGrise** [comment]
I'm not sure where the 'Memory Issue' title came from, it looks to me like an issue with 2 different maps.

**Comment by MikeMillerGIS** [comment]
@SteveGrise updated the title

**Comment by jessnoo** [comment]
@MikeMillerGIS @SteveGrise Yes -- this is still an issue

in this example from the 1.4 testing, the input mapping file is for fGDB to eGDB -- but the oracle DB isn't updated -- and the messages indicate my previous test with a shapefile was used.

![image](https://cloud.githubusercontent.com/assets/6181441/20082561/a8d04058-a50b-11e6-9c87-d07972d5e9eb.png)

**Comment by SteveGrise** [comment]
Code was only checking one map not all maps. Should always check all maps, also should not need to do that if the layer is selected and passed as a layer object.

**Comment by jessnoo** [comment]
validated with sprint 1 drop for dec 2016
