### ISSUE TITLE
AGOL Feature Service to AGOL Feature Service failure

### ISSUE THREAD

**Issue by ChrisBuscaglia** [Esri/data-assistant#81]
AGOL Feature Service to AGOL Feature Service failure

Adding features 8000:8100
Add features to Feature Service failed
Python Error messages:Traceback Info:  File "C:\Users\chri4819\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaPublish.py", line 280, in addFeatures    lenAdded = len(result['addResults'])
null
Data Assistant Update Failed, see messages for details

Message: 
Data Assistant - Append Data
Process completed with 3 errors
When any errors are encountered tools will report a general failure - even though the results may be still be satisfactory.
Check the Geoprocessing log and errors reported along with the output data to confirm.
Completed script AppendData...

 
Shared Services:
<Source>http://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/rest/services/TaxDistribution/FeatureServer/0</Source>
      <Target>http://services.arcgis.com/b6gLrKHqgkQb393u/arcgis/rest/services/TaxParcelQuery_9ace448f739e4ac6838a03ccf9b343cb/FeatureServer/0</Target>

I would suggest moving the append functionality to the append tool that now works with feature services.

[SourceTarget.zip](https://github.com/Esri/data-assistant/files/572738/SourceTarget.zip)

**Comment by SteveGrise** [comment]
Improved error messages if updating a Feature Service fails. Not sure why it would fail after 8000 features, looks like a problem communicating with the server or something else outside of the DA code.

**Comment by ChrisBuscaglia** [comment]
Steve, were you able to reproduce this issue, I believe that it has to do with a geometry issue and is why I would suggest using the append.

**Comment by SteveGrise** [comment]
My understanding is that I have been asked to address issues for the December release to minimize code changes. I have not looked at changing the code to use Append, it would be a significant change in the way the tools work. That is planned as part of the enhanced functionality after Dec 6. 

There are several potential ways to read this issue so I need someone to clarify the request. For now I am treating it as providing a better error message when an error occurs, for all the notes here I had no idea there was a potential geometry issue.

**Comment by SteveGrise** [comment]
Also I don't understand how a bad geometry could come from a feature service but not load to a feature service? Are you talking about a different issue that was shp to Feature Service @ChrisBuscaglia ?

**Comment by SteveGrise** [comment]
I believe @ChrisBuscaglia comments are related to #84. The best I can do when feature service updates fail is write a better error message since Append would involve significant rework.

**Comment by ChrisBuscaglia** [comment]
@SteveGrise This is a different issue and different source data than #84.

**Comment by SteveGrise** [comment]
The best I can do is write a better error message if a feature service update fails for the December release. In that case the server response did not include ['addResults'] and printed the error above.

**Comment by ChrisBuscaglia** [comment]
Looks good
