### ISSUE TITLE
Preview/Append fail on rows with a raster field that is not null 

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#83]
Not sure if it is intended to be supported by the tool, but Raster fields raise an error if they have a non null value in the source. Attached is some sample data that contains a couple rows with populated raster data fields.

[SampleData.zip](https://github.com/Esri/data-assistant/files/575783/SampleData.zip)

FIPS_CNTRY:GM #0
ISO_3DIGIT:DEU #1
CNTRY_NAME:Germany #2
POP_CNTRY:81436300.0 #3
Hyperlink:http://www.germany.travel/en/index.html #4
Continent:Europe #5
length:56.11495241570024 #6
some_date:2013-01-31 15:45:47.000001 #7
date_only:2013-01-25 00:00:00 #8
some_int:57 #9
some_float:0.57 #10
blob:None #11
short:1 #12
float:0.9876543283462524 #13
raster:C:\Users\chri4849\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dla.gdb\DATAASSISTANT201611071010\raster.OBJECTID = 7 #14
guid:None #15
Python Error messages:
Traceback Info:
  File "C:\Users\chri4849\AppData\Local\ESRI\ArcGISPro\AssemblyCache\{28142961-b645-420f-ba2a-72bcf8212558}\GPTools\arcpy\dlaFieldCalculator.py", line 235, in setFieldValues
    updateCursor.updateRow(row)
Exception caught: unable to update row

**Comment by SteveGrise** [comment]
Exclude raster field from config files and field calculator.

**Comment by chris-fox** [comment]
Verified
