### ISSUE TITLE
When there's no map in project - New File fails for the following combinations

### ISSUE THREAD

**Issue by jessnoo** [Esri/data-assistant#85]
**Source - Target combinations that fail:**
- Shapefile to File Geodatabase
- File Geodatabase to Enterprise Geodatabase (oracle)

**Repro Steps:**

1. Create a new Pro project that's empty (no maps, no scenes, etc)
2. Click New File
3. Navigate to a source file that's a shapefile
4. Navigate to a target file that's in a fgdb
5. Run tool

>> Fails
![image](https://cloud.githubusercontent.com/assets/6181441/20080717/0a58c7b6-a500-11e6-8038-82f042cff54b.png)

Alternate Test:

1. Add a map to the project
2. Load the shp into the map
3. Update new map parameters so that the source shp is pointing to the layer file

>> Passes
![image](https://cloud.githubusercontent.com/assets/6181441/20080734/263906c6-a500-11e6-958c-2b51e71ef6c5.png)

**Comment by SteveGrise** [comment]
Tested in dev environment, appears to be resolved.

**Comment by jessnoo** [comment]
verified with sprint 1 drop for dec 2016 release
