### ISSUE TITLE
Left and Right method 'Show Results' returns None if the string value is less than the length of the number of characters specified.

### ISSUE THREAD

**Issue by chris-fox** [Esri/data-assistant#87]
In the screenshot below we are applying a method of Left to the country name field using a value of 4 which shows the correct results:

![image](https://cloud.githubusercontent.com/assets/6796763/20101054/4312ab2e-a58e-11e6-966e-1975d1f36223.png)

Below is the same method but with a value of 8. Now several country names are shown as None because the length of their name is less than 8 characters long. I would expect it would just show the full name in this case.

![image](https://cloud.githubusercontent.com/assets/6796763/20101110/8155865e-a58e-11e6-92e6-fe5e3a54d2aa.png)

**Comment by SteveGrise** [comment]
Fixed the issue, ready for testing.

**Comment by ChrisBuscaglia** [comment]
@chris-fox can you please verify and close when ready?

**Comment by chris-fox** [comment]
Verified in Sprint2 branch
