### ISSUE TITLE
Data Mapper window should be scroll-able or more responsive

### ISSUE THREAD

**Issue by jessnoo** [Esri/data-assistant#88]
The Configure Data Mapping dialog has a couple opportunities:

1. if the pane it is in is made smaller than that width, no scroll bars appear. and it doesn't feel like it should have a minimum width so wide. 

![image](https://cloud.githubusercontent.com/assets/6181441/20118979/898c9524-a5bb-11e6-9bc0-fb8154d9a9ff.png)

2. also, it should, by default show up where the GP dialog shows up --- NOT over the Contents tab. the rest of the workflow winds up driving the user back to the Contents tab -- from a UX perspective, I think it's better co-located with the Project and GP windows.  If it were co-located with the Project and GP windows, then i think the width thing wouldn't be such a big deal

**Comment by previnWong** [comment]
On initial load, there is no scroll bar.
![image](https://cloud.githubusercontent.com/assets/11183838/23914298/cf6daafc-08a2-11e7-8bd0-b11f0e762881.png)

Once you do choose a config file, then the scroll bars appears.
![image](https://cloud.githubusercontent.com/assets/11183838/23914333/e7891e1e-08a2-11e7-80aa-b5be3afb060a.png)

**Comment by MikeMillerGIS** [comment]
verified
